/**
 * IPA fetcher for European languages (espeak-ng on the server).
 * CJK (ko/ja/zh) is skipped — those already display reading/Hangul which
 * fully convey pronunciation.
 */
import { supabase } from '@src/api/supabase';
import { translatePOS } from '@src/utils/normalizeResult';
import type { WordMeaning } from '@src/types/word';
import { withTimeout } from '@src/utils/timeout';

// Russian/CJK voice data isn't included in the espeak-ng WASM bundle, so we
// only attempt IPA for Latin-script European languages.
const SUPPORTED_LANGS_FOR_IPA = new Set([
  'en', 'es', 'fr', 'de', 'it', 'pt',
]);

export function ipaSupported(language: string): boolean {
  return SUPPORTED_LANGS_FOR_IPA.has(language);
}

/**
 * Latin-script content check. Espeak with a French/German/etc. voice will
 * happily process Hangul or CJK characters by reading each codepoint's name
 * (e.g. "한국인" → French phoneticization of "i accent aigu / ..."), producing
 * meaningless IPA strings that get cached and displayed. We reject any text
 * containing non-Latin letter characters before requesting IPA.
 *
 * Allowed: ASCII letters, extended Latin (À-ÿ, Latin Extended), digits,
 * spaces, common punctuation. Rejected: Hangul, CJK, Cyrillic, kana, Arabic.
 */
function isLatinText(text: string): boolean {
  // Strip allowed non-letter chars first (digits, spaces, punctuation).
  const letters = text.replace(/[\d\s.,!?'"\-:;()/—]/g, '');
  if (!letters) return false;
  // Every remaining char must be in Latin / Latin Extended Unicode blocks.
  for (const ch of letters) {
    const cp = ch.codePointAt(0)!;
    const isBasicLatin = (cp >= 0x41 && cp <= 0x5A) || (cp >= 0x61 && cp <= 0x7A);
    const isLatin1 = cp >= 0xC0 && cp <= 0xFF;            // Latin-1 Supplement letters
    const isLatinExtA = cp >= 0x100 && cp <= 0x17F;       // Latin Extended-A
    const isLatinExtB = cp >= 0x180 && cp <= 0x24F;       // Latin Extended-B
    if (!isBasicLatin && !isLatin1 && !isLatinExtA && !isLatinExtB) {
      return false;
    }
  }
  return true;
}

/** Skip IPA when the only meanings are "expression" (idioms/numbers/symbols). */
export function ipaApplicable(meanings: WordMeaning[] | undefined): boolean {
  if (!meanings || meanings.length === 0) return false;
  return meanings.some((m) => translatePOS(m.partOfSpeech, 'en') !== 'expression');
}

interface IpaResponse {
  ipa?: string;
  cached?: boolean;
  error?: string;
}

/**
 * Fetch IPA from the edge function — DISABLED.
 *
 * The bundled espeak-ng WASM (npm:espeak-ng@1.0.2) silently produces
 * letter-spelling garbage for non-English languages (verified: "König"
 * returns `kˈɑː ˈapzˌat‍s nˈiːk` while host espeak-ng 1.52 produces correct
 * `kˈøːnɪç`). IPA is now generated by the AI directly inside word-lookup
 * (see prompts.ts `ipa` field rule), so this client-side fetch is no
 * longer needed.
 *
 * Kept as a no-op stub to avoid touching every call site; can be removed
 * once we confirm AI-generated IPA quality is acceptable.
 */
export async function fetchIpa(_text: string, _language: string): Promise<string | null> {
  return null;
}
