// Client-side mirror of supabase/functions/_shared/realign-examples.ts.
// Re-routes each example to the meaning slot whose translated definition
// tokens best match the example's translation. Used when ingesting data
// that wasn't realigned server-side — primarily curated_words content,
// which was generated by v2 and stored raw in results_by_target_lang
// without the v3 stitch realignment safety net.
//
// Keep in sync with the server copy. Pure TS, no platform deps.
import type { WordExample, WordMeaning } from '@src/types/word';

const STOP_WORDS = new Set([
  'the', 'a', 'an', 'is', 'are', 'was', 'were', 'be', 'been', 'being',
  'of', 'to', 'in', 'on', 'at', 'by', 'for', 'with', 'as', 'from',
  'my', 'your', 'his', 'her', 'its', 'our', 'their',
  'and', 'or', 'but', 'so', 'if', 'then', 'than',
  'this', 'that', 'these', 'those', 'it', 'i', 'we', 'they', 'you',
  'do', 'did', 'does', 'have', 'has', 'had',
]);

// Korean particles attached to nouns/verbs we strip so token matching works.
// Keep in sync with the server copy in _shared/realign-examples.ts.
const KO_PARTICLE_RE =
  /(?:으로서|에게서|에서는|에서도|에서|에게|한테|께서|이라도|까지|부터|조차|마저|처럼|보다|으로|와|과|이며|이고|이라|이다|입니다|이요|이|가|을|를|은|는|의|도|만|와|로|랑|이랑|뿐|이나|나|네|니|냐|군요|네요|군|구나|지요|지)$/;
function stripKoreanParticle(t: string): string {
  if (!/[가-힯]/.test(t)) return t;
  const stripped = t.replace(KO_PARTICLE_RE, '');
  return stripped.length >= 1 ? stripped : t;
}

function tokenize(s: string): Set<string> {
  const raw = (s || '')
    .toLowerCase()
    .replace(/[(),.;:!?'"`“”、。!?]/g, ' ')
    .split(/\s+/)
    .filter((t) => t.length > 1);
  return new Set(raw.map(stripKoreanParticle).filter((t) => t.length >= 1));
}

export function realignExamplesByTranslation(
  meanings: WordMeaning[],
  examples: WordExample[],
  targetLang: string,
): WordExample[] {
  if (!targetLang) return examples;
  if (meanings.length < 2 || examples.length === 0) return examples;

  const meaningTokenSets = meanings.map((m) => tokenize(m.definition || ''));
  const tokenFreq: Record<string, number> = {};
  for (const set of meaningTokenSets) {
    for (const t of set) tokenFreq[t] = (tokenFreq[t] ?? 0) + 1;
  }
  const discrim = meaningTokenSets.map((set) => {
    const out = new Set<string>();
    for (const t of set) if (tokenFreq[t] === 1) out.add(t);
    return out;
  });

  const out: WordExample[] = [];
  const usedSlots = new Set<number>();

  for (const ex of examples) {
    const exTokens = tokenize(ex.translation || '');
    if (exTokens.size === 0) continue;

    let bestIdx = -1;
    let bestScore = 0;
    for (let i = 0; i < meanings.length; i++) {
      if (usedSlots.has(i)) continue;
      let score = 0;
      for (const t of discrim[i]) {
        if (STOP_WORDS.has(t)) continue;
        if (exTokens.has(t)) score++;
      }
      if (score > bestScore) {
        bestScore = score;
        bestIdx = i;
      }
    }

    if (bestScore > 0 && bestIdx >= 0) {
      out.push({ ...ex, meaningIndex: bestIdx });
      usedSlots.add(bestIdx);
      continue;
    }

    const orig = ex.meaningIndex ?? 0;
    if (orig >= 0 && orig < meanings.length && !usedSlots.has(orig)) {
      out.push(ex);
      usedSlots.add(orig);
      continue;
    }
    for (let i = 0; i < meanings.length; i++) {
      if (!usedSlots.has(i)) {
        out.push({ ...ex, meaningIndex: i });
        usedSlots.add(i);
        break;
      }
    }
  }

  out.sort((a, b) => (a.meaningIndex ?? 0) - (b.meaningIndex ?? 0));
  return out;
}
